# 1. Packages

 - Python은 여러 유용한 툴들을 라이브러리의 형태인 package로 저장하고 있음
 - 예를 들면
    - "math" package 안에 여러 mathematical function들이 있음
 - Packages를 불러오려면
    - from math import log
      - "math"라는 package로 부터 log라는 함수를 불러오라는 의미4
    - from math import *
      - "math" package의 모든 함수를 불러올 수 있음
      
 - python의 math package는 complex number는 지원하지 않음. float 지원
 - complex number를 다루는 package는 "cmath" package 사용 (float도 지원)

# 2. Modules
 
- 큰 Package의 경우 그 안에 smaller sub-packages를 갖는 경우 있음. 그것이 module
- module은 "."으로 구분
- 대표적인 것이 numpy package
    - numpy package 안에 linear algebra, Fourier transforms 등이 있음
        - ex) Linear algebra modlue - numpy.linalg
        - ex) Fourier transform module - numpy.fft
    - 사용 예시
        - from numpy.linalg import inv

# 3. Built-in Functions

- 특정 packages를 불러들이지 않고 기본적으로 가지고 있는 function
- 별다른 import 과정 필요 없음


- float, int, complex : datatype 바꿔주는 함수
- abs : absolute value or modulus (절대값)
- input, print
- ...

# 4. "IF" Statement

- 프로그램에서 어떤 조건이 있을 때 가장 기본이 되는 뼈대
- 형태
    - 반드시 if 조건 뒤에 ":" 붙여줘야함
    - if 조건 :

            조건이 만족할 때 수행할 내용
    - "else"

        if 조건 :
            조건이 만족할 때 수행할 내용
        else :
            조건이 만족하지 않을 때 수행할 내용

    - "elif"

        if 조건 :
            조건이 만족할 때 수행할 내용
        elif 조건2 :
            조건2가 만족할 때 수행할 내용

- if x==1 :
- if x > 1 :
- if x >= 1 :
- if x < 1 :
- if x <= 1 :
- if x != 1 :

- if x>10 or x<1 :
- if x<=10 and x>=1 :



# 5. "WHILE" Statement

- ~하는 동안 계속 ~ 해라

- 형태

    while 조건 :
        조건이 만족할 경우 반복할 내용
        
- While loop
  - 조건문 내에 "and", "or" 등을 사용할 수 있음
  - break, continue

In [3]:
# break의 예시

x=14
while x>10 :
    print ("This is greater than ten. Try again")
    x = int(input("Enter a number : "))
    if x==111 :
        break

This is greater than ten. Try again
Enter a number : 13
This is greater than ten. Try again
Enter a number : 2


# 6. Lists and Arrays

-  list : python에서 가장 기본이 되는 컨테이너
  - "elements"를 배열의 형태로 보관
  - 이 elements는 같은 type의 변수일 필요가 없음
      - ex) [1, 2.5, 3+4.6j]
  - list 선언법
      - r = [1, 2, 3, 4, 5, 56, 67, 32] 
      - r[0], r[1], r[2]

In [10]:
r = [1, 2, 4, 6, 7, 9, 12, 23, 34, 56, 36, 54]
r?
r[0]
r[:]

[1, 2, 4, 6, 7, 9, 12, 23, 34, 56, 36, 54]

In [11]:
a = r
print(a)
a[3]=5
print(a)
print(r) # a를 바꿔주면 r도 함께 바뀜

[1, 2, 4, 6, 7, 9, 12, 23, 34, 56, 36, 54]
[1, 2, 4, 5, 7, 9, 12, 23, 34, 56, 36, 54]
[1, 2, 4, 5, 7, 9, 12, 23, 34, 56, 36, 54]


In [ ]:
# a=r을 했을 때 a와 r이 함께 바뀌는 것을 방지하기 위해
a = r.copy()

# 7. Lists

r=[1.0, 1.5, -2.2]

- total = sum(r)
- mean = sum(r)/len(r)
- max(r)
- min(r)

- log(r)
    - math package의 log함수에서 list는 지원되지 않음. 이럴 경우,
    - map(log, r) 사용
    
- append
    - list에 새로운 element를 추가하고 싶을 경우 사용
    - r.append(6.1)
- pop
    - list의 elements 중 가장 마지막 값을 출력해주고 list에서 그 값을 없애버림
    - pop에 index를 주고 싶은 경우
        - r.pop(0) : 0번째 element를 출력해주고 없애버림.
- empty list도 만들 수 있음
    - ex) r = []

In [13]:
list(map(log, r))

[0.0,
 0.6931471805599453,
 1.3862943611198906,
 1.6094379124341003,
 1.9459101490553132,
 2.1972245773362196,
 2.4849066497880004,
 3.1354942159291497,
 3.5263605246161616,
 4.02535169073515,
 3.58351893845611,
 3.9889840465642745]

# 8. Arrays

- 입력한 순서대로 보관해주는 컨테이너
- array의 element의 개수는 고정됨
    - 내부 값 자체는 바꿀 수 있으나 (크기가 고정되는 선에서)
    - element를 추가하거나 제거할 수 없음
- element의 type이 모두 다 같아야 하며, 그 type을 유지해야함
- 계산의 수행은 list보다 빨라 많이 사용함
    - 2-dimension, 3-dimension을 만들어서 matrix algebra를 하는 것을 지원
    - vector와 matrix처럼 행동하기 때문에, 수학 계산을 바로 적용 가능
- array는 list보다 훨씬 빠름

- array는 built-in 함수가 아니라 numpy에 구현이 되어 있음
    - from numpy import zeros
    - a = zeros(4, float)
        - size 4에 0을 채워넣은 float type의 array를 만들어라
        
- 2차원 array 만들기
    - zeros([m, n], float)
        - 예를 들면, a = zeros([3, 4], float)
        
- ones 함수
    - zeros와 비슷하게 array를 만드는 함수
    - zeros가 0으로 채웠다면 ones는 1로 채움
    - from numpy import ones

- empty 함수
    - array를 만드는 함수인데
    - 어떤 값이 assign되어 있는지 알지 못함
    - from numpy import empty
    - 예시) a = empty(4, float)

- array 함수
    - 어떤 list의 element를 그대로 한채 array로 바꿔줄 수 있음
    - 예시) r = [1.0, 1.5, -2.2] r이라는 list를
        - a = array(r, float)  : list를 array로 바꿔줌
        - a = array([1.0, 1.5, -2.2], float)
    - 2차원의 경우
        - a = array([[1, 2, 3], [4, 5, 6]], int) # list의 list 가능
    

# * 각 elements 불러오는 법

","로 연결된 것을 tuple이라고 함 ex) [1, 1]

- list를 불러올 때
    - list의 index는 integers나 slices만 가능, tuple은 불가능
    - list[0][1] 가능, list[0, 1] 불가능, list [0:] 가능
- array를 불러올 떼
    - array[0][1] 가능, array[1, 3] 가능, array[0:] 가능


In [19]:
from numpy import zeros
from numpy import array

a=zeros(4, float)
a[1]=1 # a의 1번째를 1로 변경

b = zeros([3, 4], float)
print(b)

# list의 list
c = [1, 4, 6, 8, 23, [3, 5]]
print(c[-1]) # list가 하나의 element

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 9. Reading an array from a file

파일로부터 array를 불러오고 싶을 경우

- loadtxt 함수
    - numpy에 있는 함수로, text를 직접 읽어와 array로 저장해주는 함수
    - 2차원 array도 가능
    - from numpy import loadtxt
      a = loadtxt ("values.txt", float)
      print(a)

In [27]:
a = array([1, 2, 3, 4], int)
b = a
b[1] = 7 # a[1]도 7로 바뀜, list와 같은 현상이 일어나 
print(b)
print(a)

[1 7 3 4]
[1 7 3 4]


In [28]:
# 10. Array Arithmetics

# 아래와 같은 연산도 가능
# a[0]= a[1] + 1
# x = a[2] ** 2 - 2 * a[3] / y

from numpy import array
a = array([1, 2, 3, 4], int)
b = 2 * a # copy로 생각해서 a가 바뀐다고 b도 바뀌지 않음
print(a)
print(b)

# 아래와 같은 연산도 가능
# print(a+1)
# print(a+b)
# print(a*b) - not a dot (vector) product, vector product가 있을수도 있는데 기본적으로 element wise product임

[1 2 3 4]
[2 4 6 8]
[2 3 4 5]


In [29]:
# vector product를 하고 싶으면 dot 함수를 사용하면됨
from numpy import dot
dot(a, b)# a와 b의 vector product를 수행하게됨

60

In [30]:
a = array([[1, 3], [2, 4]], int)
b = array([[4, -2], [2, 1]], int)
c = array([[1, 2], [2, 1]], int)

print(dot(a, b) + 2*c)

[[12  5]
 [20  2]]


# 11. Built-in functions

- sum, max, min, len : 1-dimension에 대해서 사용 가능
- map function
    - b = array(map(sqrt, a), float)

- numpy 안에 min, max, size, shape이라는 함수가 정의되어 있음

In [33]:
a = array([[1, 2, 3], [4, 5, 6]], int)
print(a.size)
print(a.shape)

6
(2, 3)


# 12. "For" Loops

- 어떠한 1차원 array나 1차원 list를 가지고 있을 때, 그 list의 element를 순서대로 다 돌고 싶을때 사용
- break와 continue를 사용할 수 있음

In [4]:
# For loop 예시

r = [1, 3, 5]
for n in r :
    print(n)
    print(2*n)
print("Finished")

1
2
3
6
5
10
Finished


[0, 1, 2, 3, 4]

# 13. range function

- 연속적으로 증가하는 정수 열이 있는 list를 만듦 (integer 정수만 적용 가능)
- 예를들어, range(5)이면, list[0, 1, 2, 3, 4]가 만들어지는 것
    - 개념적으로는 list를 만드는 것이지만 사실은 그 안에서 iterator로 만들어지는 것 (진짜 만들면 메모리를 너무 많이 차지해서)
    - 진짜 물리적인 list를 만드려면, list(range(5))


- range(5) gives [0, 1, 2, 3, 4]
- range(2, 8) gives [2, 3, 4, 5, 6, 7]
- range(2, 20, 3) gives [2, 5, 8, 11, 14, 17]
- range(20, 2, -3) gives [20, 17, 14, 11, 8, 5]

In [ ]:
# range function

range(5)
list(range(5))

r = range(5)
for n in r :
    print("Hello again")
    
r = range(5)
for n in r :
    print(n**2)

for n in range(5) :
    print(n**2)

# 14. Arange function from numpy

- range function과 같은 기능을 하지만 "float 소수"에 적용 가능한 함수
- iterator를 만들어 내는 것이 아니라 array를 만들어냄 (실제 물리적인)


- arange(1, 8, 2) gives [1, 3, 5, 7] 
- arange(1.0, 8.0, 2.0) gives [1.0, 3.0, 5.0, 7.0]

# 15. linspace function from numpy

- floating point value를 가지고 있으면서, array를 만들어냄
- linspace(a, b, c) : a에서 시작해서 b를 포함하고 등간격으로 하며, 그 안에 size가 c인(c개의 element를 가진) array를 만들어냄


- linspace(2.0, 2.8, 5) gives array[2.0, 2.2, 2.4, 2.6, 2.8]

In [ ]:
# 16. User-defined Functions

# 형태
# def 함수이름(함수에서 받고자 하는 argument) : 
    # 계산할 내용
    # return 출력할 내용

# 정의한 function 내부의 변수는 그 정의한 함수 내부에서만 적용이 되는 local variable로 적용이 됨

# define function을 여러 개 만들어 define.py로 저장하고 불러올 때, 그 중 myfunction이라는 function도 있다면,
# from define import myfunction
# 이라고 불러와주면 됨

# 예시1
def factorial(n) :
    f = 1.0
    for k in range(1, n+1) :
        f *= k
    return f

# 예시2
def cartesian(r, theta) :
    x = r*cos(theta)
    y = r*sin(theta)
    position = [x, y]
    return position

# 17. Multiple assignment

- x, y = a, b

- define function에서 return 값을 "a, b" 이렇게 tuple의 형태로 할 수 있으나 만약 그렇게 할 경우,
    - x, y = f(1)
    - 이렇게 받아주는 것도 tuple의 형태로 받아줘야함

소인수분해 !!!